language: csharp
dotnet: 2.2.101
mono: none
notifications:
  email: false
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
    - os: osx
      osx_image: xcode9.1
install:
  - dotnet restore
script:
  - dotnet build -c Release
